AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  Sample SAM Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  AddtoFavouritesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: AddtoFavourites/
      Handler: app.lambda_handler
      Runtime: python3.8


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AddtoFavouritesFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AddtoFavouritesFunction.Arn
  AddtoFavouritesFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AddtoFavouritesFunctionRole.Arn
