AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  Sample SAM Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  AddtoFavouritesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: AddtoFavourites/
      Handler: AddToFavourites.add_to_favourites
      Runtime: python3.8
      Events:
        AddtoFavourites:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /atf
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AddtoFavouritesApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/atf/"
  AddtoFavouritesFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AddtoFavouritesFunction.Arn
  AddtoFavouritesFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AddtoFavouritesFunctionRole.Arn
