AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  untitled

  Sample SAM Template for untitled

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  NewPairingsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main/
      Handler: NewPairing.newpairing
      Runtime: python3.8

  viewFavouritesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main/
      Handler: ViewFavourites.view_favourites
      Runtime: python3.8
      Policies:
        # Give DynamoDB Full Access to your Lambda Function
        - AmazonDynamoDBFullAccess
      Events:
        viewFavourites:
          Type: AWS::ApiGateway::RestApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /viewFavourites
            Method: post

  ViewUserPairingsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main/
      Handler: ViewUserPairings.view_user_pairings
      Runtime: python3.8
      Policies:
        # Give DynamoDB Full Access to your Lambda Function
        - AmazonDynamoDBFullAccess
      Events:
        ViewUserPairings:
          Type: AWS::ApiGateway::RestApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /viewUserPairings
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  viewFavouritesFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt viewFavouritesFunction.Arn
  viewFavouritesFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt viewFavouritesFunctionRole.Arn

  NewPairingsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt NewPairingsFunction.Arn
  NewPairingsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt NewPairingsFunctionRole.Arn

  ViewUserPairingsFunction:
    Description: "ViewUserPairings Lambda Function ARN"
    Value: !GetAtt ViewUserPairingsFunction.Arn
  ViewUserPairingsIamRole:
    Description: "Implicit IAM Role created for ViewUserPairings function"
    Value: !GetAtt ViewUserPairingsRole.Arn