AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Image Recognition Lambda with api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  IdentifyFoodItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main/
      Handler: IdentifyFoodItem.identify_food_item
      Runtime: python3.8
      Policies:
        # Give DynamoDB Full Access to your Lambda Function
        - AmazonDynamoDBFullAccess
      Events:
        IdentifyFoodItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IdentifyFoodItemApi:
    Description: "API Gateway endpoint URL for Prod stage for IdentifyFoodItem function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/IdentifyFoodItem/"
  IdentifyFoodItemFunction:
    Description: "IdentifyFoodItem Lambda Function ARN"
    Value: !GetAtt IdentifyFoodItemFunction.Arn
  IdentifyFoodItemIamRole:
    Description: "Implicit IAM Role created for IdentifyFoodItem function"
    Value: !GetAtt IdentifyFoodItemFunctionRole.Arn